### ISSUE TITLE
Question about training/testing celltypes

### ISSUE THREAD

**Issue by ninashenker** [MiraldiLab/maxATAC#116]
Hi maxATAC team. 

Really awesome work!! Is there anyway to know what cell types were trained and tested on for each transcription factor? Specifically- I am interested in using your model to predict CTCF in GM12878 and IMR-90 to then predict Hi-C. I wanted to compared your predicted CTCF to CTCF Chip-seq. Was the CTCF model trained on those cell types?

Best,
Nina

**Comment by tacazares** [comment]
Hello, 
The final models available are trained using all cell types. We did perform "round-robin" training as well (leave 1 cell type out and use the rest for training). We have models available for CTCF that excluded GM12878 or IMR-90 during training. If you are interested we could provide the h5 files for prediction.
Thanks for your interest and we are interested in seeing your results!
Tareian
