### ISSUE TITLE
pseudo-bulk

### ISSUE THREAD

**Issue by drosop** [MiraldiLab/maxATAC#126]
Hi,

How can I create pseudo-bulk atac count matrix? Also, during summing up the count data, do you binarize it?

Thank you,

**Comment by emiraldi** [comment]
Hello!

The input to maxATAC is not a count matrix but rather a signal track: https://github.com/MiraldiLab/maxATAC#pseudo-bulk-scatac-seq

You can generate the signal track using, for example, Seurat's "CallPeaks()" for a specific cell population of interest, using the additional.args='-B --SPMR' option, see more here: https://stuartlab.org/signac/reference/callpeaks

Hope this helps!

**Comment by drosop** [comment]
Hi @emiraldi 

Thank you for your response.

Im confused with this step "First, convert the .tsv.gz output fragments file from CellRanger into pseudo-bulk specific fragment files. Then, use maxatac prepare with each of the fragment files in order to generate a normalized bigwig file for input into maxatac predict." How to achieve this?

Thank you,

**Comment by tacazares** [comment]
Hello, 
A typical workflow would start with the scATACseq analysis that identifies a pseudo-bulk population of cells. You would then find all of the cell barcodes for that pseudo-bulk and subset your CellRanger fragment file into a separate file that represents all fragments associated with the pseudo-bulk population. You would then generate a signal track that represents the Tn5 cut sites for that population. See the following links for more detailed information. 

https://github.com/MiraldiLab/maxATAC/wiki/ATAC-seq-Data-Processing

https://github.com/MiraldiLab/maxATAC/wiki/prepare#scatac-seq
