### ISSUE TITLE
import error _OrderedEnqueuer_ tensorflow.keras.utils

### ISSUE THREAD

**Issue by martinezvbs** [MiraldiLab/maxATAC#129]
Hi, 

While I was installing maxATAC with Conda 

`conda create -n maxatac -c bioconda python=3.9 samtools wget bedtools ucsc-bedgraphtobigwig pigz`
`pip install maxatac`

# Test installation
`maxatac -h`

I noticed the error "import error _OrderedEnqueuer_ tensorflow.keras.utils" ...

In case someone sees the same error, this can be solved by

`!pip install tensorflow-gpu==2.8.0`

Taken from [issue/61468](https://github.com/tensorflow/tensorflow/issues/61468)

Greetings

**Comment by simontimmins** [comment]
I have also had a similar problem after trying to install Maxatac with conda, however after running !pip install tensorflow-gpu==2.8.0, which appeared to be successful, I still got the following error after calling maxatac -help:
ImportError: libcrypto.so.3: cannot open shared object file: No such file or directory
Thanks for your help!

**Comment by ANRudrapatna** [comment]
Hi! Thanks for reaching out!
Do you have openSSL installed in your conda environment? If so, what version do you have? 

Akshata

**Comment by ANRudrapatna** [comment]
I have seen this error when using older versions of OpenSSL - try upgrading your version of OpenSSL in the conda environment to version 3.3.0! 
Hope this helps! Please let us know if you continue to have issues or have any other questions!

Akshata

**Comment by ANRudrapatna** [comment]
Thank you for letting us know - we really appreciate it! 
Feel free to reach out any time if you have any questions!

Akshata Rudrapatna
