### ISSUE TITLE
Make sure the maxATAC python package can be installed on python 3.7/3.8/3.9 on both Ubuntu and macOS

### ISSUE THREAD

**Issue by michael-kotliar** [MiraldiLab/maxATAC#63]
`maxATAC` python package should be easily installed with all required dependencies on Ubuntu 18.04/20.04 and macOS with pre-installed python 3.7/3.8/3.9.

**The task is finished, when:**
- we can run `maxatac --help` command for any Python/OS combination with exit code 0
- we have a test for it and proper documentation

**This will require:**
- [x] Define the list of working dependencies for each python version. The list of working and tested dependencies should be saved in the same GitHub repo. When installing with pip, they will be provided through `--constraint` argument.
- [x] Find a solution for installing not python dependencies if they are also required (bedtools, samtools, etc).
- [ ] Make automatic tests for running the installation on every Python/OS combination. Here I can help because I've already implemented a similar thing here https://github.com/Barski-lab/cwl-airflow/blob/master/tests/run_conformance_tests_docker.sh

**Comment by tacazares** [comment]
@michael-kotliar Do you have any experience setting up CI and upload to pypi?
