### ISSUE TITLE
Finalize Code Base

### ISSUE THREAD

**Issue by FaizRizvi** [MiraldiLab/maxATAC#80]
- [x] Delete Refactor and Develop branches
- [x] Discuss hg38 meta file management
- [x] Make PyPi package (MUST INCLUDE 'maxatac prepare')
- [x] Make Docker containers
- [x] Modify install instructions accordingly
- [x] Setup docs_rendering (with https://readthedocs.org/ -  need to be public repo for that)
- [x] Test install
- [x] maxATAC_data needs to be properly linked to maxATAC
- [x]  Repository is too big. We will need to remove all files that were added here by mistake.
- [x]  Add LICENSE
- [x] Add CODE_OF_CONDUCT.md
- [x] Add CONTRIBUTING.md
- [ ] #104
- [x]  Make sure we are not bound to Python 3.6 as it will be deprecated soon
- [x] Set author and author_email in setup.py
- [x] Make sure we don't have anything identical to the code we used as an example!

**Comment by tacazares** [comment]
We need to update the docs for prediction, specifically variant based predictions. We also need to clarify that the -m flag will use the model where the -tf is used to find the correct model for a TF.
