### ISSUE TITLE
variants_bed invalid int value

### ISSUE THREAD

**Issue by hrayjones** [MiraldiLab/maxATAC#93]
Hello, 

I am trying to run maxatac variants and I have the following error:
`maxatac variants: error: argument -variants_bed/--variants_bed: invalid int value: 'variants_1based.bed'`

My variants_bed file looks like this:
`head variants_1based.bed` 
`chr1	758351	758351	G`
`chr1	770502	770502	A`
`chr1	770988	770988	G`
`chr1	785001	785001	T`
`chr1	785910	785910	C`
`chr1	787290	787290	C`

I have tried supplying the SNPs in this bed file as 0-based or 1-based, but neither worked. I have also tried removing "chr". Please can you advise me where I might be going wrong?

Many thanks in advance! 
Helen

**Comment by tacazares** [comment]
> Hello, 
> 
> 
> 
> I am trying to run maxatac variants and I have the following error:
> 
> `maxatac variants: error: argument -variants_bed/--variants_bed: invalid int value: 'variants_1based.bed'`
> 
> 
> 
> My variants_bed file looks like this:
> 
> `head variants_1based.bed` 
> 
> `chr1	758351	758351	G`
> 
> `chr1	770502	770502	A`
> 
> `chr1	770988	770988	G`
> 
> `chr1	785001	785001	T`
> 
> `chr1	785910	785910	C`
> 
> `chr1	787290	787290	C`
> 
> 
> 
> I have tried supplying the SNPs in this bed file as 0-based or 1-based, but neither worked. I have also tried removing "chr". Please can you advise me where I might be going wrong?
> 
> 
> 
> Many thanks in advance! 
> 
> Helen

Hello Helen,

Thanks so much for trying our method and posting this issue!  I am sorry for your frustration having encountered this error. It looks like the argument parser for this function was set up wrong. It is not an issue with your input. 

https://github.com/MiraldiLab/maxATAC/blob/bcc2eb68871ba1db27d3ebed2c20524311a86d02/maxatac/utilities/parser.py#L839

The fix will require me to change a few lines of code and test. I also noticed a few other arguments that had the wrong style assigned. I will work on it this evening and post an update for you. Thanks a bunch for pointing this out!

Tareian

**Comment by tacazares** [comment]
I was able to reproduce your error with my own data. 

```pre
/Users/caz3so/opt/anaconda3/envs/maxatac/bin/python /Users/caz3so/workspaces/miraldiLab/maxATAC/maxatac/bin/maxatac variants -m /Users/caz3so/scratch/maxatac_test/predict_input/CTCF_20.h5 -s /Users/caz3so/scratch/databank/genome_inf/hg38/hg38.2bit -signal /Users/caz3so/scratch/maxatac_test/predict_input/GM12878__slop20bp_RP20M_minmax01.bw -variants_bed /Users/caz3so/scratch/20211012_maxATAC_atopicDerm_samples/data/variants/AD2_variants.bed -chroms chr20 -n CTCF_variants_test -o /Users/caz3so/scratch/maxatac_test/variants
                             _______       _____ 
                          /\|__   __|/\   / ____|
 _ __ ___   __ ___  __   /  \  | |  /  \ | |     
| '_ ` _ \ / _` \ \/ /  / /\ \ | | / /\ \| |     
| | | | | | (_| |>  <  / ____ \| |/ ____ \ |____ 
|_| |_| |_|\__,_/_/\_\/_/    \_\_/_/    \_\_____|
                                                 
                                                 

usage: maxatac variants [-h] -m MODEL -signal INPUT_BIGWIG [-o OUTPUT] -n NAME
                        [-s SEQUENCE] [-chroms CHROMOSOMES] -variants_bed
                        VARIANTS_BED [-roi ROI]
                        [--loglevel {fatal,error,warning,info,debug}]
                        [--blacklist BLACKLIST] [--chrom_sizes CHROM_SIZES]
                        [--step_size STEP_SIZE]
maxatac variants: error: argument -variants_bed/--variants_bed: invalid int value: '/Users/caz3so/scratch/20211012_maxATAC_atopicDerm_samples/data/variants/AD2_variants.bed'

Process finished with exit code 1

```

I updated the code to fix this problem. 

```pre
/Users/caz3so/opt/anaconda3/envs/maxatac/bin/python /Users/caz3so/workspaces/miraldiLab/maxATAC/maxatac/bin/maxatac variants -m /Users/caz3so/scratch/maxatac_test/predict_input/CTCF_20.h5 -s /Users/caz3so/scratch/databank/genome_inf/hg38/hg38.2bit -signal /Users/caz3so/scratch/maxatac_test/predict_input/GM12878__slop20bp_RP20M_minmax01.bw -variants_bed /Users/caz3so/scratch/20211012_maxATAC_atopicDerm_samples/data/variants/AD2_variants.bed -chroms chr20 -n CTCF_variants_test -o /Users/caz3so/scratch/maxatac_test/variants
                             _______       _____ 
                          /\|__   __|/\   / ____|
 _ __ ___   __ ___  __   /  \  | |  /  \ | |     
| '_ ` _ \ / _` \ \/ /  / /\ \ | | / /\ \| |     
| | | | | | (_| |>  <  / ____ \| |/ ____ \ |____ 
|_| |_| |_|\__,_/_/\_\/_/    \_\_/_/    \_\_____|
                                                 
                                                 

[2022-04-19 23:01:26,816]
Create prediction regions
[2022-04-19 23:04:08,128]
Making sequence specific predictions for: /Users/caz3so/scratch/maxatac_test/predict_input/GM12878__slop20bp_RP20M_minmax01.bw 
Writing files with name: CTCF_variants_test 
Output bigwig: /Users/caz3so/scratch/maxatac_test/variants/CTCF_variants_test.bw 
Output bedgraph: /Users/caz3so/scratch/maxatac_test/variants/CTCF_variants_test.bg 
Prediction Windows: /Users/caz3so/scratch/maxatac_test/variants/CTCF_variants_test_windows.bed 
Sequence file: /Users/caz3so/scratch/databank/genome_inf/hg38/hg38.2bit 
MaxATAC model: /Users/caz3so/scratch/maxatac_test/predict_input/CTCF_20.h5 
Chromosome(s): ['chr20'] 
Variants Bed: /Users/caz3so/scratch/20211012_maxATAC_atopicDerm_samples/data/variants/AD2_variants.bed
[Errno 17] File exists: '/Users/caz3so/scratch/maxatac_test/variants'

Process finished with exit code 0
```

I found some additional problems that also needed corrected. 
* There were a few other arguments that had the wrong `dtype`. 
* The `chroms` argument was missing the `nargs='+'` argument. 
* The variants.py file line 68 was also incorrect and had `args.signal` instead of `args.input_bigwig`.

**Comment by hrayjones** [comment]
Hi Tareian, 

Brilliant, thank you for your quick fix!

Helen

**Comment by FaizRizvi** [comment]
pypi package update to 1.0.4
https://pypi.org/project/maxatac/1.0.4/

**Comment by hrayjones** [comment]
Hi Tareian,

I updated maxatac to 1.0.4 but had a different error:
<img width="786" alt="Screenshot 2022-04-22 at 11 02 28" src="https://user-images.githubusercontent.com/63010941/164684859-c69c3b86-0dd4-4cea-bf83-1ade8af64ab4.png">

I think I have fixed it by adding `chrom_sizes` to def `import_roi_bed` on line 152 of variant_tools.py and `args.chrom_sizes` to the call to `import_roi_bed` on line 27 of variants.py. It now seems to run OK.

Thank you for your help on this!

Helen

**Comment by emiraldi** [comment]
Thanks, Helen! Your reporting is very helpful to us!

**Comment by FaizRizvi** [comment]
Hi Helen,

Thank you for all your help! If you get a chance can you test the pypi package? (https://pypi.org/project/maxatac/1.0.5/). I have updated the changes on the pypi package.

**Comment by hrayjones** [comment]
Hi Faiz, 

I have now tested the variants function of the pypi package version 1.0.5. It runs for me, and I get a resultant .bg file. However, I have not yet been able to generate the .bw file (with this version or previous versions). I've attached the error file here in case you can spot anything that is going wrong - I think it could be the runtime error? In the predict function I am able to obtain both the .bg and the .bw files.

Many thanks,
Helen
[5541708.pbs.ER.txt](https://github.com/MiraldiLab/maxATAC/files/8686130/5541708.pbs.ER.txt)

**Comment by hrayjones** [comment]
Hi Faiz,

Here was the command:
<img width="858" alt="Screenshot 2022-05-16 at 15 30 24" src="https://user-images.githubusercontent.com/63010941/168616581-2f212b51-9f95-48b0-9e4f-db005b586284.png">

In fact I've just noticed that I specified the chromosomes option twice... I wonder if that could have affected it?

The input bed files are here:
[chr22_variants.txt](https://github.com/MiraldiLab/maxATAC/files/8700995/chr22_variants.txt)
[chr22_roi.txt](https://github.com/MiraldiLab/maxATAC/files/8700996/chr22_roi.txt)

Thank you for looking into this!
Helen

**Comment by tacazares** [comment]
I was benchmarking peak-centric predictions and noticed there was unexpected poor performance. I found the error was how the bins were being created. The pybedtools windowmaker function will produce windows that are not all the same size. These windows are dropped if they are not 1,024 bp wide. If a peak is not 1,024 bp wide, it will window it to the peak size. If the peak is less than 1,024 bp, then it is being discarded. This will require updating the code for: https://github.com/MiraldiLab/maxATAC/blob/4ad3cdc3f4eab06ebbe490c5da70ba42a4d4d2a4/maxatac/utilities/prediction_tools.py#L81
